#应用或包名称
name: roll_demo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

#应用或包依赖的其它包或插件
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 新添加的依赖

  # 国际化
  flutter_localizations:
    sdk: flutter

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^0.3.13
  flutter_webview_plugin: ^0.3.11
  # 设备信息
  device_info: ^0.4.0+1
  package_info: ^0.4.0+3
  # 英语单词
  english_words: ^3.1.3
  # 网络请求
  dio: ^2.1.13
  cookie_jar: ^1.0.0
  # sp
  shared_preferences: ^0.5.2+2
  # 本地json对象存储
  localstorage: ^2.0.0

  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3
  # 解析html标签
  flutter_html: ^0.10.4

  #provider 依赖
  provider: 3.0.0+1

  # UI
  oktoast: ^2.1.7
  cached_network_image: ^1.1.1
  # 下拉刷新
  pull_to_refresh: ^1.5.6
  # 实时矢量设计和动画
  flare_flutter: ^1.5.15
  # xml解析
  xml: ^3.5.0
  # xml转换json
  xml2json: ^4.0.0
  # 数据库
  sqflite: ^1.1.6
  # 看图片
  photo_view: ^0.4.2
  # svg----这个控件真是饱受挫折呀！
  flutter_svg: ^0.13.1
  # html解析
  html: ^0.14.0+3
  # 评分
  launch_review: ^2.0.0
  # third_app
  share: 0.6.2+1 #分享
  # 调用系统分享的Flutter组件，支持分享文本、图片、视频和文件
  share_extend: "^1.1.5"
  # 加载url
  url_launcher: ^5.1.0 #启动第三方app
  # 定位
  flutter_amap_location_plugin: ^1.0.0
  # 高德2D地图插件 https://github.com/simplezhli/flutter_2d_amap
  flutter_2d_amap:
    #依赖存储在Git仓库中的包
    git:
      url: https://github.com/simplezhli/flutter_2d_amap.git
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.0
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.0+17
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.1+1
  # 打开文件，android更新下载安装包用
  open_file: ^2.0.3
  # 生成JSON序列化模板
#  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Your other dev_dependencies here
  # 生成JSON序列化模板
#  build_runner: ^1.0.0
#  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
# flutter相关的配置选项
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 指定 assets（资源）
  assets:
    - assets/image/
    - assets/image/store/
    - assets/image/goods/
    - assets/image/order/
    - assets/animations/
    - assets/svgs/

  fonts:
    - family: kuaile
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
    - family: kangxi
      fonts:
        - asset: assets/fonts/TpldKhangXiDictTrial.otf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
